# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application # name of the workflow

# this part means that this code runs when we push only main branch
on: # which action workflow to be activated
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  tests: # we change this line to "tests"
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']
      fail-fast: false

    runs-on: ${{ matrix.os }} # here we changed so that it uses all "os" we defined

    steps:
    - uses: actions/checkout@v3 # this line download from github
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }} # special matrix with list of 2 python versions
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build documentation
    
      run: |
        sphinx-build doc _build
